---
#
# Workflow that creates an aggregated store of all harvested vocabulary databases
#   from a list of sources either defined a json file, eventually created from
#   a SparQL query.
#
name: Harvest Vocabularies
permissions: {}
on:
  schedule:
  - cron: '0 4 * * *'
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/harvest.yml'
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/harvest.yml'
env:
  CI: true
  CLI_VERSION: '0.0.8'
  BRANCH: harvest
jobs:
  harvest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      # if: github.event_name != 'pull_request'
      with:
        persist-credentials: false

    - name: List repositories to harvest
      id: list-repos
      shell: bash
      run: |
        /usr/bin/python3 -m scripts.harvest https://schema.gov.it/sparql --format text 1> repositories.txt

        cat repositories.txt
    - name: Download schema_gov_it_tools.bin
      run: |
        set -e
        ARTIFACT_URL=https://github.com/teamdigitale/dati-semantic-csv-apis/releases/download/${{ env.CLI_VERSION }}/schema_gov_it_tools.bin

        curl -fL --show-error \
          "${ARTIFACT_URL}" \
          -o /usr/local/bin/schema_gov_it_tools.bin

        chmod +x /usr/local/bin/schema_gov_it_tools.bin
        /usr/local/bin/schema_gov_it_tools.bin --version

    - name: Harvest vocabularies
      id: harvest
      shell: bash
      run: |
        sed 's/^[[:space:]]*//' repositories.txt | xargs /usr/local/bin/schema_gov_it_tools.bin \
          --log-level debug \
          apistore \
          collect \
          --skip-not-found \
          --force \
          --output "${RUNNER_TEMP}/vocabularies.db"

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      # if: github.event_name != 'pull_request'
      with:
        ref: ${{ env.BRANCH }}
        path: harvest-branch
        persist-credentials: true

    - name: Publish to harvest branch
      # if: github.event_name != 'pull_request'
      shell: bash
      run: |
        cp "${RUNNER_TEMP}/vocabularies.db" harvest-branch/vocabularies.db
        cd harvest-branch
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add vocabularies.db
        git diff --cached --quiet && echo "No changes to publish." && exit 0
        git commit -m "chore: update vocabularies.db [$(date -u +%Y-%m-%dT%H:%MZ)]"
        git push
